# Use AlmaLinux 9 as the base image (RHEL 9 compatible)
FROM almalinux:9

# Install all necessary build dependencies using dnf
# - 'Development Tools' group: Provides gcc, make, etc.
# - pam-devel: Crucial for PAM C headers and development libraries.
RUN dnf install -y epel-release && \
    dnf install -y gcc \
        make \
        glibc-devel \
        pam-devel \
        gzip \
        pandoc && \
    dnf clean all

# Set the working directory inside the container.
# This is where your source code will be mounted.
WORKDIR /usr/src/app

